### ISSUE TITLE
Strings Not Translated

### ISSUE THREAD

**Issue by cibersheep** [ubports/sync-monitor#11]
Strings for nextCloud, ownCloud and Generic CalDAV are not translated.

![image](https://user-images.githubusercontent.com/6640041/60149186-24eec700-97d4-11e9-9084-8929635344bb.png)

**Comment by cibersheep** [comment]
I see now that sync-monitor is not in https://translate.ubports.com

Do we have to add them? Translate the po and MR here?

**Comment by mardy** [comment]
Pinging @Flohack74 as he's our translation expert :-)

**Comment by Flohack74** [comment]
Solved in https://translate.ubports.com/projects/ubports/sync-monitor/
