### ISSUE TITLE
Fail to configure account "xxx@xxxcom/nextcloud" 

### ISSUE THREAD

**Issue by ernesst** [ubports/sync-monitor#4]
Currently we have the Nextcloud online account authentification working. However some persons experiment a problem during the discovering of the dav calendars only with Nextcloud online account. 

Sync-monitor.log gives 
```
the sync-monitor says something like:
Athenticated !!!
Fetching remote calendars (wait...)
Account with empty sources!: 0
Fail to configure account "xxx@xxxcom/nextcloud" 0
Account sync error "xxx@xxxcom/nextcloud" "nextcloud-caldav" "0"
```

In the file https://github.com/ubports/sync-monitor/blob/calDav/src/sync-account.cpp 
line 908 : 
```
    // Use well-known url that will re-direct to the correct path
    if (providerName().toLower() == "owncloud") {
        syncUrl += QStringLiteral("/remote.php/caldav");
}
```

I guess we should add a similar **IF** for nextcloud account in order to enable the caldav sync to fix it. 

I cannot generate a PR as it's above my competencies.

Ps : I don't have this problem I guess because my server is configured with apache rewrite to remove index.php etc...

**Comment by mardy** [comment]
Thanks @ernesst, this looks like the reason for it! I'll prepare a fix for it!

**Comment by mymike00** [comment]
so, can this issue be closed?

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/sync-monitor/-/issues/4

Sorry for your inconvenience.
